version: "3.7"

networks:
  benetwork:

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hibernate
    volumes:
      - ./database/create-schema:/docker-entrypoint-initdb.d/:z
      - ./database/data:/var/lib/postgresql/data:z
    ports:
      - "9500:5432"
    networks:
      - benetwork

  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "admin"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
    networks:
      - benetwork

