spring:
  datasource:
    url: jdbc:postgresql://localhost:9500/hibernate
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true


