spring:
  datasource:
    url: jdbc:postgresql://localhost:9500/hibernate
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        search:
          backend:
            hosts: localhost:9200
            protocol: http
            username: elastic
            password: admin
          schema_management:
            strategy: drop-and-create
